<?php

use Illuminate\Database\Seeder;

class BehaviorsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('behaviors')->delete();

        $behaviors = [
            [
                'id'              => 1,
                'behavior'        => 'Aware of how they are perceived',
                'active'          => 1,
                'created_at'      => new DateTime(),
                'updated_at'      => new DateTime(),
                'deleted_at'      => null,
                'type'            => 'score',
                'likert_scale_id' => 1,
            ],
            [
                'id'              => 2,
                'behavior'        => 'Builds trusting relationships',
                'active'          => 1,
                'created_at'      => new DateTime(),
                'updated_at'      => new DateTime(),
                'deleted_at'      => null,
                'type'            => 'score',
                'likert_scale_id' => 1,
            ],
            [
                'id'              => 3,
                'behavior'        => 'Challenges me',
                'active'          => 1,
                'created_at'      => new DateTime(),
                'updated_at'      => new DateTime(),
                'deleted_at'      => null,
                'type'            => 'score',
                'likert_scale_id' => 1,
            ],
            [
                'id'              => 4,
                'behavior'        => 'Controls behavior based on the situation',
                'active'          => 1,
                'created_at'      => new DateTime(),
                'updated_at'      => new DateTime(),
                'deleted_at'      => null,
                'type'            => 'score',
                'likert_scale_id' => 1,
            ],
            [
                'id'              => 5,
                'behavior'        => 'Demonstrates effective listening skills',
                'active'          => 1,
                'created_at'      => new DateTime(),
                'updated_at'      => new DateTime(),
                'deleted_at'      => null,
                'type'            => 'score',
                'likert_scale_id' => 1,
            ],
            [
                'id'              => 6,
                'behavior'        => 'Develops my skills',
                'active'          => 1,
                'created_at'      => new DateTime(),
                'updated_at'      => new DateTime(),
                'deleted_at'      => null,
                'type'            => 'score',
                'likert_scale_id' => 1,
            ],
            [
                'id'              => 7,
                'behavior'        => 'Does the right thing',
                'active'          => 1,
                'created_at'      => new DateTime(),
                'updated_at'      => new DateTime(),
                'deleted_at'      => null,
                'type'            => 'score',
                'likert_scale_id' => 1,
            ],
            [
                'id'              => 8,
                'behavior'        => 'Does what is expected of them',
                'active'          => 1,
                'created_at'      => new DateTime(),
                'updated_at'      => new DateTime(),
                'deleted_at'      => null,
                'type'            => 'score',
                'likert_scale_id' => 1,
            ],
            [
                'id'              => 9,
                'behavior'        => 'Exceeds expectations',
                'active'          => 1,
                'created_at'      => new DateTime(),
                'updated_at'      => new DateTime(),
                'deleted_at'      => null,
                'type'            => 'score',
                'likert_scale_id' => 1,
            ],
            [
                'id'              => 10,
                'behavior'        => 'Facilitates productive interactions among team',
                'active'          => 1,
                'created_at'      => new DateTime(),
                'updated_at'      => new DateTime(),
                'deleted_at'      => null,
                'type'            => 'score',
                'likert_scale_id' => 1,
            ],
            [
                'id'              => 11,
                'behavior'        => 'Gives constructive feedback to others',
                'active'          => 1,
                'created_at'      => new DateTime(),
                'updated_at'      => new DateTime(),
                'deleted_at'      => null,
                'type'            => 'score',
                'likert_scale_id' => 1,
            ],
            [
                'id'              => 12,
                'behavior'        => 'Holds all team members accountable',
                'active'          => 1,
                'created_at'      => new DateTime(),
                'updated_at'      => new DateTime(),
                'deleted_at'      => null,
                'type'            => 'score',
                'likert_scale_id' => 1,
            ],
            [
                'id'              => 13,
                'behavior'        => 'Inspiring and motivating',
                'active'          => 1,
                'created_at'      => new DateTime(),
                'updated_at'      => new DateTime(),
                'deleted_at'      => null,
                'type'            => 'score',
                'likert_scale_id' => 1,
            ],
            [
                'id'              => 14,
                'behavior'        => 'Makes ethical decisions',
                'active'          => 1,
                'created_at'      => new DateTime(),
                'updated_at'      => new DateTime(),
                'deleted_at'      => null,
                'type'            => 'score',
                'likert_scale_id' => 1,
            ],
            [
                'id'              => 15,
                'behavior'        => 'Makes others better',
                'active'          => 1,
                'created_at'      => new DateTime(),
                'updated_at'      => new DateTime(),
                'deleted_at'      => null,
                'type'            => 'score',
                'likert_scale_id' => 1,
            ],
            [
                'id'              => 16,
                'behavior'        => 'Makes people want to work for them',
                'active'          => 1,
                'created_at'      => new DateTime(),
                'updated_at'      => new DateTime(),
                'deleted_at'      => null,
                'type'            => 'score',
                'likert_scale_id' => 1,
            ],
            [
                'id'              => 17,
                'behavior'        => 'Positively embraces change',
                'active'          => 1,
                'created_at'      => new DateTime(),
                'updated_at'      => new DateTime(),
                'deleted_at'      => null,
                'type'            => 'score',
                'likert_scale_id' => 1,
            ],
            [
                'id'              => 18,
                'behavior'        => 'Positively leads change',
                'active'          => 1,
                'created_at'      => new DateTime(),
                'updated_at'      => new DateTime(),
                'deleted_at'      => null,
                'type'            => 'score',
                'likert_scale_id' => 1,
            ],
            [
                'id'              => 19,
                'behavior'        => 'Positively receives feedback from others',
                'active'          => 1,
                'created_at'      => new DateTime(),
                'updated_at'      => new DateTime(),
                'deleted_at'      => null,
                'type'            => 'score',
                'likert_scale_id' => 1,
            ],
            [
                'id'              => 20,
                'behavior'        => 'Prevents interpersonal issues',
                'active'          => 1,
                'created_at'      => new DateTime(),
                'updated_at'      => new DateTime(),
                'deleted_at'      => null,
                'type'            => 'score',
                'likert_scale_id' => 1,
            ],
            [
                'id'              => 21,
                'behavior'        => 'Prevents interpersonal issues among team',
                'active'          => 1,
                'created_at'      => new DateTime(),
                'updated_at'      => new DateTime(),
                'deleted_at'      => null,
                'type'            => 'score',
                'likert_scale_id' => 1,
            ],
            [
                'id'              => 22,
                'behavior'        => 'Provides constructive feedback',
                'active'          => 1,
                'created_at'      => new DateTime(),
                'updated_at'      => new DateTime(),
                'deleted_at'      => null,
                'type'            => 'score',
                'likert_scale_id' => 1,
            ],
            [
                'id'              => 23,
                'behavior'        => 'Removes barriers',
                'active'          => 1,
                'created_at'      => new DateTime(),
                'updated_at'      => new DateTime(),
                'deleted_at'      => null,
                'type'            => 'score',
                'likert_scale_id' => 1,
            ],
            [
                'id'              => 24,
                'behavior'        => 'Sets high but fair expectations',
                'active'          => 1,
                'created_at'      => new DateTime(),
                'updated_at'      => new DateTime(),
                'deleted_at'      => null,
                'type'            => 'score',
                'likert_scale_id' => 1,
            ],
            [
                'id'              => 25,
                'behavior'        => 'Shares knowledge with others',
                'active'          => 1,
                'created_at'      => new DateTime(),
                'updated_at'      => new DateTime(),
                'deleted_at'      => null,
                'type'            => 'score',
                'likert_scale_id' => 1,
            ],
            [
                'id'              => 26,
                'behavior'        => 'Shares resources with others',
                'active'          => 1,
                'created_at'      => new DateTime(),
                'updated_at'      => new DateTime(),
                'deleted_at'      => null,
                'type'            => 'score',
                'likert_scale_id' => 1,
            ],
            [
                'id'              => 27,
                'behavior'        => 'Works productively with others',
                'active'          => 1,
                'created_at'      => new DateTime(),
                'updated_at'      => new DateTime(),
                'deleted_at'      => null,
                'type'            => 'score',
                'likert_scale_id' => 1,
            ],
        ];

        DB::table('behaviors')->insert($behaviors);
    }
}
