<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class UsersTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @throws
     *
     * @return void
     */
    public function run()
    {
        DB::table('users')->delete();
        $imgPath = base_path().'/resources/images/profile_seeds/';
        $users = [
                [
                    'id'                                     => 1,
                    'anonymous_id'                           => Str::uuid()->toString(),
                    'first_name'                             => 'Alec',
                    'last_name'                              => 'Baker',
                    'email'                                  => 'alec@develapme.com',
                    'password'                               => Hash::make(config('develapme.password.default')),
                    'status'                                 => 'active',
                    'timezone'                               => 'US/Eastern',
                    'country_dial_code'                      => '+1',
                    'password_change_required'               => 0,
                    'push_enabled'                           => 0,
                    'created_at'                             => new DateTime(),
                    'updated_at'                             => new DateTime(),
                    'image_path'                             => $imgPath.'1.jpeg',
                ],
                [
                    'id'                       => 2,
                    'anonymous_id'             => Str::uuid()->toString(),
                    'first_name'               => 'Tony',
                    'last_name'                => 'Petrucci',
                    'email'                    => 'tony@develapme.com',
                    'password'                 => Hash::make(config('develapme.password.default')),
                    'status'                   => 'active',
                    'timezone'                 => 'US/Eastern',
                    'country_dial_code'        => '+1',
                    'password_change_required' => 0,
                    'push_enabled'             => 0,
                    'created_at'               => new DateTime(),
                    'updated_at'               => new DateTime(),
                    'image_path'               => $imgPath.'2.jpeg',

            ],
            [
                'id'                       => 3,
                'anonymous_id'             => Str::uuid()->toString(),
                'first_name'               => 'Cliff',
                'last_name'                => 'Tironi',
                'email'                    => 'cliff@develapme.com',
                'password'                 => Hash::make(config('develapme.password.default')),
                'status'                   => 'active',
                'timezone'                 => 'US/Eastern',
                'country_dial_code'        => '+1',
                'password_change_required' => 0,
                'push_enabled'             => 0,
                'created_at'               => new DateTime(),
                'updated_at'               => new DateTime(),
                'image_path'               => $imgPath.'3.jpeg',
            ],
            [
                'id'                       => 4,
                'anonymous_id'             => Str::uuid()->toString(),
                'first_name'               => 'Michael',
                'last_name'                => 'Rivera',
                'email'                    => 'michael@develapme.com',
                'password'                 => Hash::make(config('develapme.password.default')),
                'status'                   => 'active',
                'timezone'                 => 'US/Eastern',
                'country_dial_code'        => '+1',
                'password_change_required' => 0,
                'push_enabled'             => 0,
                'created_at'               => new DateTime(),
                'updated_at'               => new DateTime(),
                'image_path'               => $imgPath.'4.jpeg',
            ],
            [
                'id'                       => 5,
                'anonymous_id'             => Str::uuid()->toString(),
                'first_name'               => 'Cory',
                'last_name'                => 'LaFleur',
                'email'                    => 'cory.lafleur@develapme.com',
                'password'                 => Hash::make(config('develapme.password.default')),
                'status'                   => 'active',
                'timezone'                 => 'US/Eastern',
                'country_dial_code'        => '+1',
                'password_change_required' => 0,
                'push_enabled'             => 0,
                'created_at'               => new DateTime(),
                'updated_at'               => new DateTime(),
                'image_path'               => $imgPath.'5.jpeg',
            ],
            [
                'id'                       => 6,
                'anonymous_id'             => Str::uuid()->toString(),
                'first_name'               => 'Robin',
                'last_name'                => 'Goffman',
                'email'                    => 'robin.goffman@develapme.com',
                'password'                 => Hash::make(config('develapme.password.default')),
                'status'                   => 'active',
                'timezone'                 => 'US/Eastern',
                'country_dial_code'        => '+1',
                'password_change_required' => 0,
                'push_enabled'             => 0,
                'created_at'               => new DateTime(),
                'updated_at'               => new DateTime(),
                'image_path'               => $imgPath.'6.jpeg',
            ],
            [
                'id'                       => 7,
                'anonymous_id'             => Str::uuid()->toString(),
                'first_name'               => 'Elaine',
                'last_name'                => 'Byerley',
                'email'                    => 'elaine.byerley@develapme.com',
                'password'                 => Hash::make(config('develapme.password.default')),
                'status'                   => 'active',
                'timezone'                 => 'US/Eastern',
                'country_dial_code'        => '+1',
                'password_change_required' => 0,
                'push_enabled'             => 0,
                'created_at'               => new DateTime(),
                'updated_at'               => new DateTime(),
                'image_path'               => $imgPath.'7.jpeg',
            ],
            [
                'id'                       => 8,
                'anonymous_id'             => Str::uuid()->toString(),
                'first_name'               => 'Natalie',
                'last_name'                => 'Miller',
                'email'                    => 'natalie.miller@develapme.com',
                'password'                 => Hash::make(config('develapme.password.default')),
                'status'                   => 'active',
                'timezone'                 => 'US/Eastern',
                'country_dial_code'        => '+1',
                'password_change_required' => 0,
                'push_enabled'             => 0,
                'created_at'               => new DateTime(),
                'updated_at'               => new DateTime(),
                'image_path'               => $imgPath.'8.jpeg',
            ],
            [
                'id'                       => 9,
                'anonymous_id'             => Str::uuid()->toString(),
                'first_name'               => 'Carly',
                'last_name'                => 'Demato',
                'email'                    => 'carly.demato@develapme.com',
                'password'                 => Hash::make(config('develapme.password.default')),
                'status'                   => 'active',
                'timezone'                 => 'US/Eastern',
                'country_dial_code'        => '+1',
                'password_change_required' => 0,
                'push_enabled'             => 0,
                'created_at'               => new DateTime(),
                'updated_at'               => new DateTime(),
                'image_path'               => $imgPath.'9.jpeg',
            ],
            [
                'id'                       => 10,
                'anonymous_id'             => Str::uuid()->toString(),
                'first_name'               => 'Dan',
                'last_name'                => 'Coyle',
                'email'                    => 'dan.coyle@develapme.com',
                'password'                 => Hash::make(config('develapme.password.default')),
                'status'                   => 'active',
                'timezone'                 => 'US/Eastern',
                'country_dial_code'        => '+1',
                'password_change_required' => 0,
                'push_enabled'             => 0,
                'created_at'               => new DateTime(),
                'updated_at'               => new DateTime(),
               'image_path'                => $imgPath.'10.jpeg',
            ],
            [
                'id'                        => 11,
                'anonymous_id'              => Str::uuid()->toString(),
                'first_name'                => 'Patrick',
                'last_name'                 => 'Gleeson',
                'email'                     => 'patrick.gleeson@develapme.com',
                'password'                  => Hash::make(config('develapme.password.default')),
                'status'                    => 'active',
                'timezone'                  => 'US/Eastern',
                'country_dial_code'         => '+1',
                'password_change_required'  => 0,
                'push_enabled'              => 0,
                'created_at'                => new DateTime(),
                'updated_at'                => new DateTime(),
                'image_path'                => $imgPath.'11.jpeg',
            ],
            [
                'id'                        => 12,
                'anonymous_id'              => Str::uuid()->toString(),
                'first_name'                => 'Rebecca',
                'last_name'                 => 'Zinn',
                'email'                     => 'rebecca.zinn@develapme.com',
                'password'                  => Hash::make(config('develapme.password.default')),
                'status'                    => 'active',
                'timezone'                  => 'US/Eastern',
                'country_dial_code'         => '+1',
                'password_change_required'  => 0,
                'push_enabled'              => 0,
                'created_at'                => new DateTime(),
                'updated_at'                => new DateTime(),
                'image_path'                => $imgPath.'12.jpeg',
            ],
        ];

        foreach ($users as $userInsert) {
            $model = new App\Models\Users();
            $model->fill($userInsert);
            $model->save();
        }
    }
}
